version: '3.7'

services:
  couchdb:
    build: ./database
    expose:
      - "5984"
    ports:
      - "8002:5984"
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}

  collector:
    build: ./data-collector
    depends_on:
      - couchdb
    expose:
      - "8000"
    ports:
      - "8001:8000"
    environment:
      - DB_HOST=couchdb
      - DB_PORT=5984
      - DB_USER=${COUCHDB_USER}
      - DB_PASSWORD=${COUCHDB_PASSWORD}
      - SERVICE_NAME=data-collector
      - TRACING_EXPORTER=jaeger
      - JAEGER_AGENT_HOST_NAME=jaeger

  proxy:
    build: ./experiment-proxy
    depends_on:
      - collector
    ports:
      - "8000:8000"
    environment:
      - BACKEND_URL=http://test:8000
      - BACKEND_SERVICE=test-case
      - COLLECTOR_URL=http://collector:8000
      - SERVICE_NAME=experiment-proxy
      - TRACING_EXPORTER=jaeger
      - JAEGER_AGENT_HOST_NAME=jaeger

  test:
    build: ./tests/test-service
    expose:
      - "8000"
    ports:
      - "8003-8010:8000"
    depends_on:
      - proxy
    environment:
      - SERVICE_NAME=test-case
      - TRACING_EXPORTER=jaeger
      - JAEGER_AGENT_HOST_NAME=jaeger
      - COLLECTOR_URL=http://collector:8000
      - EXPERIMENT=1

  jaeger:
    image: jaegertracing/all-in-one
    expose:
      - "6831"
    ports:
      - "16686:16686"
    restart: always
