version: '3.7'

services:
  landing:
    image: ghcr.io/xai-demonstrator/landing-page-service:latest
    depends_on:
      - inspection
      - sentiment
      - country
    ports:
      - 8000:80

  sentiment:
    image: ghcr.io/xai-demonstrator/review-sentiment-service:latest
    depends_on:
      - jaeger
    expose:
      - 8000
    environment:
      - ROOT_PATH=/api/sentiment
      - SERVICE_NAME=sentiment-service
      - TRACING_EXPORTER=jaeger
      - JAEGER_AGENT_HOST_NAME=jaeger

  inspection:
    image: ghcr.io/xai-demonstrator/visual-inspection-service:latest
    depends_on:
      - jaeger
    expose:
      - 8000
    environment:
      - ROOT_PATH=/api/inspection
      - SERVICE_NAME=inspection-service
      - TRACING_EXPORTER=jaeger
      - JAEGER_AGENT_HOST_NAME=jaeger

  country:
    image: ghcr.io/xai-demonstrator/guess-the-country-service:latest
    depends_on:
      - jaeger
    expose:
      - 8000
    environment:
      - ROOT_PATH=/api/country
      - SERVICE_NAME=country-service
      - TRACING_EXPORTER=jaeger
      - JAEGER_AGENT_HOST_NAME=jaeger
      - GOOGLE_MAPS_API_TOKEN=${STREETVIEW_API_KEY}
      - BATCH_SIZE=${BATCH_SIZE}
      
  sales:
    image: ghcr.io/xai-demonstrator/sales-prediction-service:latest
    depends_on:
      - jaeger
    expose:
      - 8000
    environment:
      - ROOT_PATH=/api/sales
      - SERVICE_NAME=sales-service
      - TRACING_EXPORTER=jaeger
      - JAEGER_AGENT_HOST_NAME=jaeger

  jaeger:
    image: jaegertracing/all-in-one
    expose:
      - 6831
    ports:
      - 16686:16686
    restart: always
